ElPeuco/urls.py
#urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name='index'),
    path('accounts/registro', views.registro, name='registro'),
    path('accounts/loginuser', views.loginuser, name='loginuser'),
    path('cerrar_sesion', views.cerrar_sesion, name='cerrar_sesion'),
    path('CRUD/producto_list/', views.producto_list, name='producto_list'),
    path('CRUD/producto_delete/<path:id_producto>/', views.producto_delete, name='producto_delete'),
    path('CRUD/producto_add/', views.producto_create, name='producto_add'),
    path('CRUD/producto_edit/<path:id_producto>/', views.producto_update, name='producto_edit'),
    path('venta', views.venta, name='Venta'),
    path('ver_carrito', views.ver_carrito, name='ver_carrito'),
    path('ver_carrito/agregar/<int:id_producto>/', views.agregar_al_carrito, name='agregar_al_carrito'),
    path('ver_carrito/eliminar/<int:id_item>/', views.eliminar_del_carrito, name='eliminar_del_carrito'),
    path('Contacto/', views.Contacto, name='Contacto')    

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

TiendaWeb/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ElPeuco/',include('ElPeuco.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ElPeuco/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin, User

class AdministradorusuarioRegistrado(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError('El campo de correo electrónico debe estar establecido')
        email = self.normalize_email(email)
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('El superusuario debe tener is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('El superusuario debe tener is_superuser=True.')

        return self.create_user(email, password, **extra_fields)

class usuarioRegistrado(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    phone = models.CharField(max_length=15)
    birth_date = models.DateField()
    address = models.CharField(max_length=255)
    postal_code = models.CharField(max_length=7)

    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    objects = AdministradorusuarioRegistrado()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name', 'phone', 'birth_date', 'address', 'postal_code']

    def __str__(self):
        return self.email

class UserProfile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    run = models.CharField(max_length=12)
    birth_date = models.DateField()
    phone = models.CharField(max_length=15)
    address = models.CharField(max_length=255)
    postal_code = models.CharField(max_length=10)
    document_number = models.CharField(max_length=20)

class producto(models.Model):
    id_producto = models.AutoField(primary_key=True)
    descripcion_producto = models.CharField(max_length=60)
    nombre_producto = models.CharField(max_length=30)
    precio = models.IntegerField()
    foto = models.ImageField(upload_to='images/')

    def __str__(self):
        return self.id_producto

class Carrito(models.Model):
    user = models.OneToOneField(usuarioRegistrado, on_delete=models.CASCADE)
    created_el = models.DateTimeField(auto_now_add=True)

class CarritoItem(models.Model):
    carrito = models.ForeignKey(Carrito, on_delete=models.CASCADE)
    producto = models.ForeignKey(producto, on_delete=models.CASCADE)
    cantidad = models.PositiveIntegerField(default=1)
    
class Apedido(models.Model):
    id_pedido = models.AutoField(primary_key=True)
    Correo_pedido = models.EmailField()
    Titulo_Pedido = models.CharField(max_length=60)
    descripcion_pedido =  models.TextField()
    Imagen_Adjunta = models.ImageField(upload_to='images/')

ElPeuco/forms.py
from django import forms
from .models import *
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

class ProductoForm(forms.ModelForm):
    class Meta:
        model = producto
        fields = ['descripcion_producto', 'nombre_producto', 'precio', 'foto']

class FormularioRegistrousuarioRegistrado(UserCreationForm):
    class Meta:
        model = usuarioRegistrado
        fields = ['email', 'first_name', 'last_name', 'phone', 'birth_date', 'address', 'postal_code','password1', 'password2']
        widgets ={
            'email': forms.EmailInput,
            'first_name':forms.TextInput, 
            'last_name':forms.TextInput, 
            'phone':forms.TextInput(attrs={'type': 'tel'}), 
            'birth_date':forms.DateInput(attrs={'type': 'date'}), 
            'address':forms.TextInput, 
            'postal_code':forms.NumberInput,
            'password1':forms.PasswordInput, 
            'password2':forms.PasswordInput,
        }

    def __init__(self, *args, **kwargs):
        super(FormularioRegistrousuarioRegistrado, self).__init__(*args, **kwargs)
        self.fields['email'].widget.attrs.update({'id': 'id_correo', 'name': 'correo', 'placeholder': 'Ingresa correo','class': 'form-control'})
        self.fields['first_name'].widget.attrs.update({'id': 'id_nombre', 'name': 'nombre', 'placeholder': 'Escribe tu nombre','class': 'form-control'})
        self.fields['last_name'].widget.attrs.update({'id': 'id_apellido', 'name': 'apellido', 'placeholder': 'Escribe tu apellido','class': 'form-control'})
        self.fields['phone'].widget.attrs.update({'id': 'id_telefono', 'name': 'telefono', 'placeholder': '56912345678','class': 'form-control'})
        self.fields['birth_date'].widget.attrs.update({'id': 'id_fecha_nacimiento', 'name': 'fecha_nacimiento','type': 'date','class': 'form-control', 'placeholder': 'YYYY/MM/DD',})
        self.fields['address'].widget.attrs.update({'id': 'id_direccion', 'name': 'direccion', 'placeholder': 'Ingresa tu direccion','class': 'form-control'})
        self.fields['postal_code'].widget.attrs.update({'id': 'id_codigo_postal', 'name': 'codigo_postal', 'placeholder': '1234567','class': 'form-control'})
        self.fields['password1'].widget.attrs.update({'id': 'id_password1', 'name': 'password1', 'placeholder': 'ingresa contraseña','class': 'form-control'})
        self.fields['password2'].widget.attrs.update({'id': 'id_password2', 'name': 'password2', 'placeholder': 'Confirma tu contraseña','class': 'form-control'})

class FormularioInicioSesion(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(FormularioInicioSesion, self).__init__(*args, **kwargs)
        self.fields['username'].label = "Correo"
        self.fields['username'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Correo'})
        self.fields['password'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Contraseña'})


class UserForm(forms.ModelForm):
    class Meta:
        model = usuarioRegistrado
        fields = ['first_name', 'last_name', 'email']


class ContactoForms(forms.ModelForm):
    class Meta:
        model = Apedido
        fields = ['Correo_pedido', 'Titulo_Pedido', 'descripcion_pedido', 'Imagen_Adjunta']
        widgets ={
            'Correo_pedido': forms.EmailInput(attrs={'class': 'form-control'}),
            'Titulo_Pedido':forms.TextInput(attrs={'class': 'form-control'}), 
            'descripcion_pedido':forms.Textarea(attrs={'class': 'form-control'}),
        }

ElPeuco/views.py
#views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login, logout, authenticate
from .forms import FormularioRegistrousuarioRegistrado, ProductoForm, ContactoForms
from .models import producto, Carrito, CarritoItem, Apedido
from django.contrib.auth.decorators import login_required


# Create your views here.
def index(request):
    context={}
    return render(request,'index.html',context)

#-----
def producto_list(request):
    productos = producto.objects.all()
    return render(request, 'CRUD/producto_list.html', {'productos': productos})

def producto_create(request):
    if request.method == 'POST':
        form = ProductoForm(request.POST,request.FILES)
        if form.is_valid():
            form.save()
            return redirect('producto_list')
    else:
        form = ProductoForm()
    return render(request, 'CRUD/producto_add.html', {'form': form})

def producto_update(request, id_producto):
    producto_obj = get_object_or_404(producto, id_producto=id_producto)
    if request.method == 'POST':
        form = ProductoForm(request.POST, request.FILES,instance=producto_obj)
        if form.is_valid():
            form.save()
            return redirect('producto_list')
    else:
        form = ProductoForm(instance=producto_obj)
    return render(request, 'CRUD/producto_edit.html', {'form': form})

def producto_delete(request, id_producto):
    producto_obj = get_object_or_404(producto, id_producto=id_producto)
    if request.method == 'POST':
        producto_obj.delete()
        return redirect('producto_list')
    return render(request, 'CRUD/producto_delete.html', {'producto': producto_obj})


#----
def registro(request):
    if request.method == 'POST':
        form = FormularioRegistrousuarioRegistrado(request.POST)
        if form.is_valid():
            usuario = form.save()
            login(request, usuario)
            return redirect('index')
    else:
        form = FormularioRegistrousuarioRegistrado()
    return render(request, 'accounts/registro.html', {'form': form})

def loginuser(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('index') 
        else:
            return render(request, 'accounts/loginuser.html', {'error': 'Nombre de usuario o contraseña incorrectos.'})
    return render(request, 'accounts/loginuser.html')

def cerrar_sesion(request):
    logout(request)
    return redirect('index')

def venta(request):
    productos = producto.objects.all()
    return render(request,'Venta.html',{'productos':productos})

@login_required
def agregar_al_carrito(request, id_producto):
    producto_obj = get_object_or_404(producto, id_producto=id_producto)
    carrito, created = Carrito.objects.get_or_create(user=request.user)
    carrito_item, created = CarritoItem.objects.get_or_create(carrito=carrito, producto=producto_obj)
    if not created:
        carrito_item.cantidad += 1
        carrito_item.save()
    return redirect('ver_carrito')

@login_required
def eliminar_del_carrito(request, id_item):
    carrito_item = get_object_or_404(CarritoItem, id=id_item, carrito__user=request.user)
    carrito_item.delete()
    return redirect('ver_carrito')

@login_required
def ver_carrito(request):
    carrito, created = Carrito.objects.get_or_create(user=request.user)
    items = CarritoItem.objects.filter(carrito=carrito)
    total = sum(item.producto.precio * item.cantidad for item in items)
    print(total)
    return render(request, 'ver_carrito.html', {'items': items, 'total': total})


def Contacto(request):
    if request.method == 'POST':
        form = ContactoForms(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return render(request, 'Contacto.html', {'form': form, 'success': True})
    else:
        form = ContactoForms()
    return render(request, 'Contacto.html', {'form': form, 'success': False})

ElPeuco/templates/Accounts/login.html
{% extends "base.html" %}
{%load static%}

{% block cabeceratitulo %}

<title>login</title>
{% endblock %}
{% block contenido %}
<div id="login-container" class="container mt-4">
    <div id="content_form" class="d-flex flex-column justify-content-center align-items-center p-3 border rounded">
        <p class="title">Login</p>
        <form class="form" method="post" action="{% url 'login' %}" id="formulario">
            {% csrf_token %}
            <label for="username">Correo electronico</label>
            <div class="input-group">
                <input class="form-control" type="text" name="username" id="username" placeholder="">
            </div>
            <label for="password">Contraseña</label>
            <div class="input-group">
                <input class="form-control" type="password" name="password" id="password" placeholder="">
            </div>
            <div class="forgot">
                    <a rel="noopener noreferrer" href="#">Olvidaste tu contraseña?</a>
                
            </div>
            <button class="sign button-hover1" type="submit" id="submitBtn">Iniciar Sesion</button>
        </form>
    </div>
</div>
<script src="{% static 'js/iniciar_sesion.js' %}"></script>
{% endblock %}

ElPeuco/templates/Accounts/loginuser.html
{% extends "base.html" %}
{%load static%}

{% block cabeceratitulo %}

<title>login</title>
{% endblock %}
{% block contenido %}
<div id="login-container" class="container mt-4">
    <div id="content_form" class="d-flex flex-column justify-content-center align-items-center p-3 border rounded">
        <p class="title">Login</p>
        <form class="form row" method="post" action="{% url 'loginuser' %}" id="formulario">
            {% csrf_token %}
            <label for="username">Correo electronico</label>
            <div class="input-group">
                <input class="form-control" type="text" name="username" id="username" placeholder="">
            </div>
            <label for="password">Contraseña</label>
            <div class="input-group">
                <input class="form-control" type="password" name="password" id="password" placeholder="">
            </div>
            <div class="forgot">
                    <a rel="noopener noreferrer" href="#">Olvidaste tu contraseña?</a>
                
            </div>
            <button class="sign button-hover1" type="submit" id="submitBtn">Iniciar Sesion</button>
        </form>
    </div>
</div>
<script src="{% static 'js/iniciar_sesion.js' %}"></script>
{% endblock %}

ElPeuco/templates/Accounts/registro.html
{% extends "base.html" %}
{%load static%}

{% block cabeceratitulo %}
<title>Registro</title>
{% endblock %}
{% block contenido %}
<div class="container mt-4" id="caja_registro">
    <div id="content_form" class="d-flex flex-column justify-content-center align-items p-3 border rounded">
        <h1 class="mb-4">REGISTRO</h1>
        <form class="form" id="formulario" action="{% url 'registro' %}" method="post">
            {% csrf_token %}
            {{ form.non_field_errors }}
        <div >
            <label for="id_first_name">Nombre</label>
            {{ form.first_name }}
        </div>
        <div >
            <label for="id_last_name">Apellido</label>
            {{ form.last_name }}
        </div>
            <div >
                <label for="id_phone">Numero de contacto</label>
                {{ form.phone }}
            </div>
            <div >
                <label for="id_birth_date">Fecha de nacimiento</label>
                {{ form.birth_date }}
            </div>
        <div >
            <label for="id_address">Direccion</label>
            {{ form.address }}
        </div>
            <div >
                <label for="id_postal_code">Codigo postal</label>
                {{ form.postal_code }}
            </div>
        <div >
            <label for="id_email">Correo electronico</label>
            {{ form.email }}
        </div>
        <div >
            <label for="id_password1">Contraseña</label>
            {{ form.password1 }}
        </div>
        <div >
            <label for="id_password2">Confirma tu contraseña</label>
            {{ form.password2 }}
        </div>
            <button class="button-reg" type="submit" id="submitBtn">Registrarse</button>
        </form>
    </div>
</div>
<script src="{% static 'js/registro.js' %}"></script>
{% endblock %}